### ISSUE TITLE
Backlog param is not accepted 

### ISSUE THREAD

**Issue by silviucpp** [kzemek/erlang_tls#7]
Hello,

because the {backlog, nr} setting is not implemented you cannot tune the listen queue and it's timing out with a lot of concurrent connections.

Silviu

**Comment by kzemek** [comment]
Can you check whether #9 fixes the issue for you?

**Comment by silviucpp** [comment]
Yes it's ok . also you can run `netstat -Lan` and backlog is displayed there

Silviu
